#javaapi - port = 9000, node: 5000, frontend: 4200 
# mysql - emartdb, u: root, p: emartdbpass. 
# mongo - emongo, epoc 

version: '3.8'

services:
  emartdb: 
    image: mysql:8.0.33
    restart: always
    container_name: emartdb
    environment:
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books
      - MYSQL_ROOT_PASSWORD=emartdbpass
    ports: 
      - 3306:3306

  emongo: 
    image: mongo:4
    restart: always
    container_name: emongo
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports: 
      - 27017:27017

  api: 
    image: wahabkas/emart-nodeapi:latest
    container_name: api
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - emongo
      - nginx

  webapi:
    image: wahabkas/emart-webapi:latest
    container_name: webapi
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - emartdb

  client: 
    image: wahabkas/emart-client:latest
    container_name: client
    restart: always 
    ports:
      - 4200:4200
    depends_on:
      - webapi
      - api

  nginx: 
    restart: always 
    image: wahabkas/emart-nginx-api:latest
    container_name: nginx
#    volumes:
#      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"



