#javaapi - port = 9000, node: 5000, frontend: 4200 
# mysql - emartdb, u: root, p: emartdbpass. 
# mongo - emongo, epoc 

version: '3.8'

services:
  emartdbservice: 
    image: mysql
    restart: always
    container_name: emartdb
    environment:
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books
      - MYSQL_ROOT_PASSWORD=emartdbpass
    ports: 
      - 3306:3306

  emongoservice: 
    image: mongo
    restart: always
    container_name: emongo
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports: 
      - 27017:27017

  nodeapiservice: 
    build:
      context: nodeapi
    container_name: api
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - emongoservice

  javaapi:
    build:
      context: javaapi
    container_name: webapi
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - emartdbservice

  client: 
    build:
      context: client
    container_name: client
    restart: always 
    ports:
      - 4200:4200
    depends_on:
      - javaapi
      - nodeapiservice

  nginx: 
    restart: always 
    image: nginx
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    depends_on:
      - client

networks:
  default: 
    driver: bridge
    name: backend_network

